
#H2 DATABASE
#( H2 Console
#spring.h2.console.enabled=true


# Database config
#spring.datasource.url=jdbc:h2:mem:test

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update)


#PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=Meenal
spring.datasource.password=Meenal
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

#Actuator
management.endpoints.web.exposure.include=*


#Health
management.endpoint.health.show-details=always

#info
info.app.name=JobApplication
info.app.description=Job app built by Meenal
info.app.version=1.0.0
management.info.env.enabled=true

#metrics

#Shutdown
management.endpoint.shutdown.enabled=true
server.shutdown=graceful